# Generated by Django 4.2.4 on 2023-12-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_task_due_date_alter_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed']},
        ),
    ]
